//🥋 Create a Warehouse for Loading INTL_DB
CREATE OR REPLACE WAREHOUSE ADU_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
WAREHOUSE_TYPE = 'STANDARD'
AUTO_SUSPEND = 60 //60 SECONDS/1 MINUTE
AUTO_RESUME = TRUE
;

use role accountadmin;
create or replace RESOURCE MONITOR IDENTIFIER('"DAILY_1_CREDIT_LIMIT"') 
CREDIT_QUOTA = 1 
FREQUENCY = 'DAILY' 
START_TIMESTAMP = 'IMMEDIATELY' 
TRIGGERS 
ON 85 PERCENT DO SUSPEND 
ON 95 PERCENT DO SUSPEND_IMMEDIATE 
ON 75 PERCENT DO NOTIFY
;

alter ACCOUNT set RESOURCE_MONITOR = 'DAILY_1_CREDIT_LIMIT';